version: '3'

tasks:
  install:
    cmds:
      - |
        uv sync
  # Deprecated: after install, it can be called directly
  # Execute the `aitm` cli
  # call it with: task aitm -- {ARGS}
  aitm:
    cmds:
      # With uv: uv run -m gerardnico.aitm.cli {{.CLI_ARGS}}
      - |
        aitm {{.CLI_ARGS}}
  test:
    cmds:
      # we cd in tests as JetBrains by default starts the test in the tests root directory
      # verbose: uv run pytest -v
      - |
        cd tests && uv run --project .. pytest
